spring.application.name=04-java-spring-real-project
spring.main.banner-mode=off

# JDBC Properties
spring.datasource.url = jdbc:postgresql://localhost:5432/employee_directory
spring.datasource.username=postgres
spring.datasource.password=postgres


# Spring Data REST properties
spring.data.rest.base-path=/magic-api
spring.data.rest.default-page-size=3