#
# JDBC properties
#
spring.datasource.url = jdbc:postgresql://localhost:5432/employee_directory2
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# Simple Spring Security
spring.security.user.name=continental
spring.security.user.password=1234

# Logging for investigated :)
#give more information at runtime
logging.level.org.springframework.security=DEBUG